pipeline {
    agent {
        kubernetes {
            yaml '''
              apiVersion: v1
              kind: Pod
              spec:
                containers:
                - name: maven
                  image: maven:3.9.12-sapmachine-21
                  command:
                  - cat
                  tty: true
                - name: docker
                  image: docker:dind
                  securityContext:
                    privileged: true
                  tty: true
            '''
        }
    }
    stages {
        stage('Build') {
            steps {
                container('maven') {
                    sh 'mvn -B -DskipTests clean package';
                }
            }
        }
        stage('Test') {
            steps {
                container('maven') {
                    sh 'mvn test';
                }
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml';
                }
            }
        }
        stage('Deliver') { 
            steps {
                container('maven') {
                    sh './jenkins/scripts/deliver.sh';
                }
            }
        }
        stage('Docker_build') { 
            steps {
                container('docker') {
                    sh "docker build -t oandronic_java:${env.BUILD_NUMBER} .";
                    sh "docker images";
                }
            }
        }
        stage('Docker_push') {
            steps {
                container('docker') {
                    withCredentials([usernamePassword(credentialsId: 'docker-hub-creds', 
                                                    usernameVariable: 'DOCKER_USER', 
                                                    passwordVariable: 'DOCKER_PASS')]) {
                        script {
                            sh "echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin";
                            def imageName = "${DOCKER_USER}/oandronicitschool:${env.BUILD_NUMBER}";
                            sh "docker tag oandronic_java:${env.BUILD_NUMBER} ${imageName}";
                            sh "docker push ${imageName}";
                        }
                    }
                }
            }
        }
    }
}
